# Generated by Django 5.0.1 on 2024-01-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
